apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mirth-connect
  name: db-pv-claim
  namespace: mirth-connect
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
status: {}
