apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mirth-connect
  name: mc-pv-claim
  namespace: mirth-connect
spec:
  # storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
